name: Continuous Integration

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  - pull_request

env:
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Check contracts are linted
        run: forge fmt --check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clone repo
        uses: actions/checkout@v3
        with:
              submodules: recursive

      - name: Run tests
        run: forge test -vvv

  codespell:
    name: Run codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          skip: ./.git,yarn.lock
